### ISSUE TITLE
Settings button off the bottom of the screen.

### ISSUE THREAD

**Issue by Selochrome** [xchan14/larawan#3]
I am using elementary 6, Larawan seems to work fine except if you change the number of pixels in a way which (accidentally) creates a window which is Portrait format;  long enough that the bottom is below the screen and the top is right up against the top of the screen. The program, though working becomes unusable and uninstalling and reinstalling makes no difference. Is there a way to go forward with this?

**Comment by xchan14** [comment]
Hi , thanks for sending your feedback. To resolve your issue, can you answer the ff. questions so I can replicate it on my end.
1. Can you share a screenshot of your issue?
2. What's your desktop resolution?

Thank you!

**Comment by Selochrome** [comment]
Hello, 
Thanks for getting back to me. The screen resolution is 1366 x 768
and see the screen shot of the window created attached
![Screenshot from 2024-03-20 18 56 56](https://github.com/xchan14/larawan/assets/96597087/0ecd9a5f-a99f-4127-85c6-4c3f602a27b5)
.
Thanks,
S.

**Comment by xchan14** [comment]
Fix has been submitted in AppCenter and waiting for approval. In the mean time, you can uninstall the app with its data using this command `flatpak uninstall --delete-data io.github.xchan14.larawan` to return to its fresh install state.

**Comment by xchan14** [comment]
Fix has been published in AppCenter.
